import type { Metadata } from "next";
import { Source_Sans_3} from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const SourceSans3 = Source_Sans_3({
  variable: "--font-source-sans-3",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SourceSans3.variable} antialiased font-[family-name:var(--font-source-sans-3)]`}
      >
        {children}

        <Navigation />
      </body>
    </html>
  );
}
